version: '3'

services:
  mydb:
    image: stackupiss/northwind-db:v1
    volumes:
      - mydb:/var/lib/mysql
    networks:
      - mynet
  
  myapp:
    image: xindedocker/server
    environment:
      - DB_HOST=mydb
    ports:
      - 80:3000
    networks:
      - mynet
    
volumes:
  mydb:

networks:
  mynet:

    