apiVersion: v1
kind: Pod

metadata:
  name: myapp-pod
  namespace: xinspace
  labels:
    name: myapp-pod

spec:
  containers:
    - name: myapp-container
      image: stackupiss/northwind-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: DB_HOST
          value: localhost
      
      
