apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demopythonappdp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demopythonappdp
        version: v1
    spec:
      containers:
      - name: demopythonappcontainer
        image: balanus/demopythonapp
        imagePullPolicy: Always
        env:
          - name: SERVICE_VERSION
            value: v1
        ports:
        - containerPort: 6000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demopythonappdp2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demopythonappdp
        version: v2
    spec:
      containers:
      - name: demopythonappcontainer
        image: balanus/demopythonapp
        imagePullPolicy: Always
        env:
          - name: SERVICE_VERSION
            value: v2
        ports:
        - containerPort: 6000
