apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "weatherapp.fullname" . }} #dynamic name NOT ARD CODE
  namespace: {{ .Values.namespaceValue }}
spec:
  selector:
    istio: ingressgateway #controller
  servers:
  - hosts: 
    - {{ .Values.gatewayhostname }} #dynamic name NOT ARD CODE
    port:
      number: {{ .Values.gatewayport }}
      protocol: HTTP
      name: HTTP