apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "weatherapp.fullname" . }}
  namespace: {{ .Values.namespaceValue }}
spec:
  hosts:
  - {{ .Values.gatewayhostname }} #domain name coming from
  gateways:
  - {{ include "weatherapp.fullname" . }}
  http:
  - route:
    - destination:
        host: {{ include "weatherapp.fullname" . }} #kubernetes svc
