apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: myapp-hpa
  namespace: xinspace
  labels:
    name: myapp-hpa

spec:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 20
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deploy