apiVersion: v1
kind: ServiceAccount

metadata:
  name: webui-admin
  namespace: xinspace

---

# bind to cluster admin, create clusterrolebinding

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: webui-admin-crb
  namespace: xinspace

# reference that we are gonna bind to
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

subjects:
  - kind: ServiceAccount
    name: webui-admin
    namespace: xinspace